[package]
name = "filestats"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
datetime = "0.5.2"
libc = "0.2.149"
systime_converter = "0.1.0"
